# Generated by Django 5.2 on 2025-06-08 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='user_task_no',
            field=models.IntegerField(default=1),
        ),
    ]
