# Generated by Django 5.2 on 2025-06-08 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0002_todo_user_task_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='user_task_no',
        ),
    ]
